### ISSUE TITLE
Unable to connect to OBS. Attempting to reconnect {count} of {max}

### ISSUE THREAD

**Issue by SuperNov4DZN** [Streamers-Workshop/Blazebot#208]
**Describe the bug**
After enabling obs at "..\TrovoBot-master\services\obs\obs.json" "active": true," the bot fails to start throwing the following error:

```
Unable to connect to OBS. Attempting to reconnect {count} of {max}

C:\Users\user\Desktop\TrovoBot-master\services\obs\obs.js:25
                                activate();
                                ^

ReferenceError activate is not defined
    at Timeout._onTimeout (C:\Users\user\Desktop\TrovoBot-master\services\obs\obs.js:25:5)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**To Reproduce**
1. Go to '..\TrovoBot-master\services\obs'
2. Open 'obs.json'
3. Change '"active": false,' to '"active": true,'
4. Go to '..\TrovoBot-master"
5. Open the terminal
6. Run 'npm .' or 'npm index'
7. See Error

**Expected behavior**
Run normally being able to integrate custom alerts with obs 

**Desktop**
 - OS: Microsoft Windows 10 Version 2004 (OS Build 19041.572)
 - Browser: Microsoft Edge
 - Version: 86.0.622.56

**Comment by Bioblaze** [comment]
YAY <3 I love you :D first real Bug Report YIPPY~ I'll get on this ASAP ^_^

**Comment by sirblockwood101** [comment]
i notice this bug when obs is not open but when opened this error does not come up

**Comment by Bioblaze** [comment]
We will make changes to the documentation, and throw additional errors into OBS plugin for this.

**Comment by Bioblaze** [comment]
This is solved, and will be in the next release
